name: Check build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
